export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_GENRES_MOVIES_SUCCESS = 'REQUEST_GENRES_MOVIES_SUCCESS';
export const REQUEST_GENRES_SUCCESS = 'REQUEST_GENRES_SUCCESS';
export const ADD_HEART = 'ADD_HEART';
export const REMOVE_HEART = 'REMOVE_HEART';
